# Generated by Django 3.2.7 on 2021-09-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210909_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.CharField(blank=True, default='blank for now', max_length=200),
        ),
    ]
